### ISSUE TITLE
1.4.2 Failing to Start (Windows .exe)

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stigman-watcher#110]
Greetings,

I just upgraded watcher from 1.4.1 to 1.4.2 and the Windows executable is failing to start.

![image](https://github.com/NUWCDIVNPT/stigman-watcher/assets/53829030/d7b3896f-c7c4-4bbe-b469-5fb38a7ee56b)

![image](https://github.com/NUWCDIVNPT/stigman-watcher/assets/53829030/c76d17c7-8239-477f-b638-e4d15fe66426)

Switched the executable back to 1.4.1 and it started right up.

Thanks!

**Comment by cd-rite** [comment]
Thanks, @sagansapien . We have reproduced the issue, working on a fix.
