### ISSUE TITLE
DeprecationWarning in node

### ISSUE THREAD

**Issue by thukk** [NUWCDIVNPT/stigman-watcher#116]
Noticed the below message when running Watcher 1.4.3

`(node:10852) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by cd-rite** [comment]
Suspect this has to do with the older version of `got `we are using
