### ISSUE TITLE
Scans should not run concurrently, and should only run when no files are currently being processed.

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stigman-watcher#117]
This issue has evolved, and previously this issue was assuming a specific solution was needed. 
The goals are: 
Only one scan running at a time.
Scans should not run while files are still being processed from the previous run. 
Scans should be scheduled for an <interval> amount of time after work from the previous scan is complete.

Current suggested approach:
Register for queue events in scanner.
Scanner can track whether queues have work by tracking `task_queued` and `drain` events.
Scanner checks whether it can schedule itself based on status of either queue.

Old comment/title for reference:

> NextScan should be scheduled by cargo.js on cargoQueue drain, rather than being scheduled by scanner.
> 
> Scan.js always starts a new scan when an API alarm is lowered.  This is not desirable behavior.
> 
> on cargoQueue drain, schedule next scan if in "scan" mode.
> 
> Consider cancelling any running scans when an alarm is raised.

**Comment by Matte22** [comment]
@cd-rite should the last bullet, "Consider cancelling any running scans when an alarm is raised" be ignored for this issue as it it is also referenced in issue #121?

**Comment by cd-rite** [comment]
#121 is referring to _scheduled_ scans. This one is referring to cancelling an _ongoing_ scan, which may not be straightforward. 
However, I don't think it's necessary as long as our queues are paused and no extra scans get scheduled.

**Comment by cd-rite** [comment]
Another thought, when cargo drains, I think we also DONT want to schedule a scan if one is already running. 
Soooo.... this has now got more complicated. 
Also: 
If a scan runs, and finds no new files, then it should schedule the scan itself (if no scan is currently scheduled AND there is nothing queued), since cargo will never drain if queue is already empty (and so will never schedule another scan).

**Comment by Matte22** [comment]
Yup! currently working on a solution to that!
