### ISSUE TITLE
APIOffline alarm should not be raised on 400 errors

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stigman-watcher#118]
api.js line 64:
    if (e.response?.statusCode === 400 && e.response?.body?.message === 'Duplicate name') {

remove second clause of if condition (ie. all 400s)

**Comment by csmig** [comment]
This requires more design work than described above. We may need to check the specific request that errored during the request pipeline (create asset, map stig(s), post reviews).

A 400 error during asset creation must be analyzed to see if the error is from a duplicate name. If it is, the error can be logged and not rethrown. If the error results in a asset not being created for any other reason, then the error must be rethrown so the request pipeline stops.

A 400 error during any other phase of the request pipeline should be rethrown. Additional discussion is welcome if I've missed anything.

**Comment by csmig** [comment]
An addendum to the above. The API actually returns status `422 Unprocessable` when there's an [Asset name collision during creation](https://github.com/NUWCDIVNPT/stig-manager/blob/f925074badb514e580660e8267f256a03614af4d/api/source/controllers/Asset.js#L30-L32)

```javascript
        if (err.code === 'ER_DUP_ENTRY') {
          throw new SmError.UnprocessableError('Duplicate name exists.')
        }
```
