### ISSUE TITLE
Make REQUEST_TIMEOUT user configurable

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stigman-watcher#120]
Currently set in consts.js

**Comment by vogtjob** [comment]
Hi.  We're currently running the Windows executable of STIGMAN Watcher and are having an issue with a rather large collection that spawns the error "Timeout awaiting 'request' for 5000ms......"

I'm assuming this is what is being referenced here?

I was going to ask if there was an undocumented environment variable we could set, but it appears that will be in a later version.

Thanks!

**Comment by Matte22** [comment]
We're aware of the api timeout error with large collections in STIGMAN Watcher. Our team is currently working on it. Keep an eye out for the update!

**Comment by csmig** [comment]
@vogtjob The timeout you're seeing is probably the result of Watcher over fetching from the API.

While determining which Assets in a batch of results need to be created, Watcher fetches a detailed list of ***all*** the Assets in a Collection. For the largest Collections, this list too big to be returned to Watcher before the default timeout expires.

In #123 we've put a band aid on the problem by increasing the default timeout and exposing it via an envvar. The problem would be more fully addressed by refactoring the code that is over fetching to be more efficient.
