### ISSUE TITLE
doc: STIG Manager collection grant configuration needs more depth

### ISSUE THREAD

**Issue by csmig** [NUWCDIVNPT/stigman-watcher#13]
The Wiki and README mention Watcher needing a Collection grant of "Manage", but there is no description on how to accomplish that. The REQUIREMENTS portion in the Wiki should have a "STIG Manager" section that explains this.

**Comment by cd-rite** [comment]
https://github.com/NUWCDIVNPT/stigman-watcher/wiki/Requirements-and-Configuration
