### ISSUE TITLE
Windows Download

### ISSUE THREAD

**Issue by isaacmphillips** [NUWCDIVNPT/stigman-watcher#133]
You're "installation and usage" instructions specify "C:/> stigman-watcher-win.exe", but no location to get that EXE.
Where can I get a windows installation of this STIGman Watcher?

**Comment by cd-rite** [comment]
Hi @isaacmphillips You can find a .zip file of the windows exe file on our Releases page here:
https://github.com/NUWCDIVNPT/stigman-watcher/releases
From our homepage:
![image](https://github.com/user-attachments/assets/a5c38c92-facc-403d-beab-ca838ae8e05f)
