### ISSUE TITLE
Error importing SQL checklist created by Evaluate STIG

### ISSUE THREAD

**Issue by zirus001** [NUWCDIVNPT/stigman-watcher#141]
I am running into an issue with stigman watcher importing SQL checklist. I have narrowed it down to only the SQL checklist that are created by Evaluate STIG. These particular servers are not on the domain and I have a task scheduler that runs the scan every 30 days. Then stigman watcher does a one-shot to STIG Manager. Here is what I am seeing in the stigman watcher logs:

`{"timestamp":"2024-11-18T17:37:28.016Z","level":"error","component":"api","message":"Response code 500 (Internal Server Error)","code":"ERR_NON_2XX_3XX_RESPONSE","request":{"method":"GET","url":"https://server1/api/assets?collectionId=1&metadata=cklHostName%3ACSP-EPO-DB&metadata=cklWebDbSite%3Amaster&metadata=cklWebDbInstance%3ACSP-EPO-DB%5CESSEPO&projection=stigs"},"response":{"status":500,"body":{"error":"Invalid JSON text in argument 2 to function json_contains: \"Invalid escape character in string.\" at position 11.","stack":"Error: Invalid JSON text in argument 2 to function json_contains: \"Invalid escape character in string.\" at position 11.\n    at PromisePool.query (/home/node/node_modules/mysql2/promise.js:356:22)\n    at exports.queryAssets (/home/node/service/AssetService.js:225:35)\n    at exports.getAssets (/home/node/service/AssetService.js:1425:28)\n    at getAssets (/home/node/controllers/Asset.js:187:41)\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/node/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/home/node/node_modules/express/lib/router/route.js:119:3)\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\n    at /home/node/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/home/node/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/node/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/home/node/node_modules/express/lib/router/index.js:175:3)\n    at router (/home/node/node_modules/express/lib/router/index.js:47:12)\n    at operationHandlersMiddleware (/home/node/node_modules/express-openapi-validator/dist/openapi.validator.js:186:28)\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/node/node_modules/express/lib/router/index.js:328:13)"}}}
{"timestamp":"2024-11-18T17:37:28.016Z","level":"error","component":"cargo","message":"batch ended","error":{"name":"HTTPError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1731951447985,"socket":1731951447985,"lookup":1731951447985,"connect":1731951447986,"secureConnect":1731951447998,"upload":1731951447998,"response":1731951448010,"end":1731951448011,"phases":{"wait":0,"dns":0,"tcp":1,"tls":12,"request":0,"firstByte":12,"download":1,"total":26}},"message":"Response code 500 (Internal Server Error)","stack":"HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (C:\\snapshot\\stigman-watcher\\bundle.cjs:19222:36)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"batchId":1}
{"timestamp":"2024-11-18T17:37:28.017Z","level":"error","component":"cargo","message":"Response code 500 (Internal Server Error)"}
{"timestamp":"2024-11-18T17:37:28.030Z","level":"info","component":"cargo","message":"batch started","batchId":2,"size":5}
{"timestamp":"2024-11-18T17:37:31.255Z","level":"error","component":"api","message":"Response code 500 (Internal Server Error)","code":"ERR_NON_2XX_3XX_RESPONSE","request":{"method":"GET","url":"https://server1/api/assets?collectionId=1&metadata=cklHostName%3ACSP-EPO-DB&metadata=cklWebDbSite%3AePO_ESSEPO_Events&metadata=cklWebDbInstance%3ACSP-EPO-DB%5CESSEPO&projection=stigs"},"response":{"status":500,"body":{"error":"Invalid JSON text in argument 2 to function json_contains: \"Invalid escape character in string.\" at position 11.","stack":"Error: Invalid JSON text in argument 2 to function json_contains: \"Invalid escape character in string.\" at position 11.\n    at PromisePool.query (/home/node/node_modules/mysql2/promise.js:356:22)\n    at exports.queryAssets (/home/node/service/AssetService.js:225:35)\n    at exports.getAssets (/home/node/service/AssetService.js:1425:28)\n    at getAssets (/home/node/controllers/Asset.js:187:41)\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/node/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/home/node/node_modules/express/lib/router/route.js:119:3)\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\n    at /home/node/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/home/node/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/node/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/home/node/node_modules/express/lib/router/index.js:175:3)\n    at router (/home/node/node_modules/express/lib/router/index.js:47:12)\n    at operationHandlersMiddleware (/home/node/node_modules/express-openapi-validator/dist/openapi.validator.js:186:28)\n    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/home/node/node_modules/express/lib/router/index.js:328:13)"}}}
{"timestamp":"2024-11-18T17:37:31.256Z","level":"error","component":"cargo","message":"batch ended","error":{"name":"HTTPError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1731951451217,"socket":1731951451217,"lookup":1731951451217,"connect":1731951451220,"secureConnect":1731951451232,"upload":1731951451232,"response":1731951451253,"end":1731951451253,"phases":{"wait":0,"dns":0,"tcp":3,"tls":12,"request":0,"firstByte":21,"download":0,"total":36}},"message":"Response code 500 (Internal Server Error)","stack":"HTTPError: Response code 500 (Internal Server Error)\n    at Request.<anonymous> (C:\\snapshot\\stigman-watcher\\bundle.cjs:19222:36)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"batchId":2}
{"timestamp":"2024-11-18T17:37:31.256Z","level":"error","component":"cargo","message":"Response code 500 (Internal Server Error)"}
{"timestamp":"2024-11-18T17:37:31.259Z","level":"info","component":"cargo","message":"finished one shot mode"}
`

**Comment by cd-rite** [comment]
Hi @zirus001 It looks like that ckl has the cklWebDbInstance tag populated with the hostname and the instance, separated by a back slash (%5C after html encoding):  CSP-EPO-DB\ESSEPO (CSP-EPO-DB%5CESSEPO), which is not being handled properly.

Until we address this, you could remove the back-slash in that field for that file, or import the .ckls as they are via the UI, which is handling the backslash properly.

**Comment by zirus001** [comment]
Ahh i see it now. I was staring at this thing for an good hour..lol I'll just import manually for the time being. I'll keep an eye out for a new release to address the issue. Thank you for the quick response!

**Comment by cd-rite** [comment]
Hi @zirus001 Turns out the best way to address this was in the STIG Manager API itself, since watcher was in fact properly formatting that request.  The fix is included in the latest release, [1.4.19](https://github.com/NUWCDIVNPT/stig-manager/releases). Thanks for bringing this to our attention!

**Comment by zirus001** [comment]
Late to the party but you're welcome! lol
