### ISSUE TITLE
Watcher uploading files multiple times

### ISSUE THREAD

**Issue by tylerforajter** [NUWCDIVNPT/stigman-watcher#19]
Hi there!

I have been using STIGMAN watcher for a few months now.  I have noticed one interesting behavior.

Sometimes watcher will reupload a file to STIGMAN, even though the file has not been changed, modified, or updated at all.  Is there a reason this could be happening?

See picture below:
![image](https://user-images.githubusercontent.com/100237457/163458035-c9789c3d-b337-4222-aac4-95c7aa83acdf.png)

Any help would be appreciated.

Thanks!

**Comment by cd-rite** [comment]
Hi @tylerforajter There are a few ways you could get that behavior, for example... if you are run one-shot mode more than once and hit the same directory; or if you start and stop with the "add-existing" flag set; or scan mode if you remove the utilities history file, move the .ckl files in and out of the watched folder, watch more than one folder with the same .ckl files in them.  
I'd check out the options page to see if you have something set that could interact that way: https://github.com/NUWCDIVNPT/stigman-watcher/wiki/Options

If you include a log file, the top section will include all the config options you have set for the utility, and might shed some light on this. 
Thanks!

**Comment by cd-rite** [comment]
Hi @tylerforajter 
We are unable to reproduce your issue. Let us know if any of the above conditions applied, and whether you were able to resolve the issue. If you can explain how to reproduce your issue in a way that is not an effect from the settings described above, feel free to reopen this issue.
Thanks!

**Comment by tylerforajter** [comment]
Ahhh I see!  I've implemented that and will do some testing to see if that fixes the issue.

Thanks!
