### ISSUE TITLE
Add Option to Exclude Files by Name

### ISSUE THREAD

**Issue by sagansapien** [NUWCDIVNPT/stigman-watcher#24]
There is currently an environment variable to tell watcher to ignore specified directories (nice!).

Evaluate-STIG recently added a new file in the top level folder, named SummaryReport.xml. This file is being parsed and produces the following message:

`{"timestamp":"2022-05-26T13:29:39.559Z","level":"warn","component":"parser","message":"No Benchmark element","file":"<my-output-path>/<hostname>/SummaryReport.xml"}`

Additionally, this file is logged in the history.txt file which is unnecessary. 

Requesting a new option to specify file names to ignore in the watched directory.

Thanks!

**Comment by csmig** [comment]
I could do this with a new option: 
```
--ignore-glob [globs...] WATCHER_IGNORE_GLOB=<csv>
```  
Since users would be able to specify paths to directories and/or files, this new option would deprecate the current `--ignore-dir [names] WATCHER_IGNORE_DIRS=<csv>`
