### ISSUE TITLE
Use dynamic Import for 'got' ESM.

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stigman-watcher#44]
Latest versions of got only available as ESM, rather than CommonJS modules. 

Consider: 
converting Watcher project as a whole to ESM, rather than CommonJS
or
Switch to build-in Node fetch

**Comment by csmig** [comment]
Project was migrated to ESM at 7302f24727e93c2c5228c32f46fb11e39d6fc3bf
