### ISSUE TITLE
"error", "component" : "api,  "message" : "self-signed certificate in certificate chain"  No uploading to Stigman

### ISSUE THREAD

**Issue by jeremyatourville** [NUWCDIVNPT/stigman-watcher#60]
I believe I have my .env file configured correctly but I am seeing the subject message when running the standalone executable in linux.  I didn't see any option to ignore the certificate.  My first presumption is that uploads aren't happening because of this error.  Can you confirm this behavior?  We are using our own CA, not Dod signed certs.

**Comment by csmig** [comment]
I'm assuming the self-signed cert is being presented by the API service. You can't tell Watcher to ignore the self-signed certificate, but you can tell it to permit connections to an API which is using it.

Assuming the certificate is in the file `self-signed.cer` and the Watcher binary is in the same directory, you could try to invoke Watcher this way:

`env NODE_EXTRA_CA_CERTS=self-signed.crt ./stigman-watcher-linuxstatic`

**Comment by jeremyatourville** [comment]
@csmig 
I tried adding the env variable you specified.  I am still getting the same error.  Here is how my environment is laid out.

```
└── stigman
    ├── certs
    │   ├── ca
    │   │   ├── demoCA.crt
    │   │   ├── gsil-ca.cer
    │   │   └── gsil-ca.crt
    │   ├── dod
    │   │   ├── bak
    │   │   │   ├── Certificates_PKCS7_v5.9_DoD.pem.p12
    │   │   │   ├── Certificates_PKCS7_v5.9_DoD.pem.p7b
    │   │   │   ├── Certificates_PKCS7_v5.9_DoD.pem.pem
    │   │   │   ├── p7b-convert.sh
    │   │   │   └── README.md
    │   │   ├── ipa-ca.crt
    │   │   └── truststore.p12
    │   └── localhost
    │       ├── gsil-docker2-chain.crt
    │       ├── gsil-docker2.key
    │       └── localhost.crt
    ├── docker-compose.yml
    ├── kc
    │   ├── h2
    │   │   ├── keycloakdb.mv.db
    │   │   └── keycloakdb.trace.db
    │   └── stigman_realm.json
    ├── logs
    │   ├── access.log
    │   └── error.log
    ├── mkwildcard_certs
    │   ├── gsil-ca.cer
    │   ├── gsil-docker2-chain.crt
    │   ├── gsil-docker2.crt
    │   ├── gsil-docker2.csr
    │   ├── gsil-docker2.key
    │   ├── ipa-ca.crt
    │   ├── make-cert.sh
    │   ├── make-truststore.sh
    │   ├── openssl.cnf
    │   └── truststore.p12
    ├── mysql-data
    │   ├── some files ...
    │   ├── #innodb_redo
    │   │   └── some files ...
    │   ├── #innodb_temp
    │   │   └── some files ...
    │   ├── mysql
    │   │   └── some files ...
    │   ├── some files ...
    │   ├── performance_schema
    │   │   └── some files ...
    │   ├── private_key.pem
    │   ├── public_key.pem
    │   ├── server-cert.pem
    │   ├── server-key.pem
    │   ├── stigman
    │   │   └── some files ...
    │   ├── sys
    │   │   └── sys_config.ibd
    │   ├── undo_001
    │   └── undo_002
    ├── nginx
    │   ├── index.html
    │   ├── nginx.conf
    │   └── nginx-new.conf
    └── stigman-watcher
        ├── help
        ├── self-signed2.crt
        ├── self-signed.crt
        ├── stigman-watcher ##standalone binary - was renamed 
        └── swlog.txt

```


[root@gsil-docker2 stigman-watcher]# cat .env
```
WATCHER_API_BASE=https://stigman.idm.example.org/stigman/api
WATCHER_AUTHORITY=https://stigman.idm.example.org/realms/stigman
WATCHER_CLIENT_ID=stigman-watcher
#WATCHER_CLIENT_KEY=/var/docker/stigman/certs/dod/truststore.p12
WATCHER_CLIENT_SECRET=p1w3AoOgiRgNsqG9gHerfl6y9jVDyLVS
WATCHER_COLLECTION=17
WATCHER_CREATE_OBJECTS=true
WATCHER_PATH=/mnt/admin/_admin/cyber/scan_results
WATCHER_ADD_EXISTING=FALSE
WATCHER_MODE=events
WATCHER_LOG_LEVEL=debug
WATCHER_LOG_FILE=/var/docker/stigman/stigman-watcher/swlog.txt
WATCHER_LOG_FILE_LEVEL=debug
#NODE_EXTRA_CA_CERTS=self-signed.crt
NODE_EXTRA_CA_CERTS=self-signed2.crt
#NODE_EXTRA_CA_CERTS=/var/docker/stigman/certs/ca/gsil-ca.crt
#NODE_EXTRA_CA_CERTS=/var/docker/stigman/certs/ca/gsil-docker2-chain.crt
```

Here is my docker compose file:

[docker-compose.yml](https://github.com/jeremyatourville/stigman-orchestration/blob/main/docker-compose.yml)

Here is my nginx config:

[nginx.conf](https://github.com/jeremyatourville/stigman-orchestration/blob/main/nginx/nginx.conf)

I did not see NODE_EXTRA_CA_CERTS env variable listed in the options documentation.  Do I need to specify the absolute path?  You can see in my .env config I tried playing with the path from the lines I have commented out.  I also tried a few different certs.  Can you clarify what cert would be proper to use here?   Thanks.

**Comment by csmig** [comment]
The values in `.env` are read by the STIGMAN Watcher code as a substitute for real envvars and they do not change the shell's actual environment. NODE_EXTRA_CA_CERTS is used by the Node.js runtime (which executes the STIGMAN Watcher code) and to have an effect it must be set in your shell's actual environment. I'd recommend using a full path. See https://nodejs.org/api/cli.html#node_extra_ca_certsfile

One way to set the shell envvar is to execute the command provided earlier above:
 `env NODE_EXTRA_CA_CERTS=self-signed.crt ./stigman-watcher-linuxstatic`
 
Alternatively
```
$ export NODE_EXTRA_CA_CERTS=self-signed.crt
$ ./stigman-watcher-linuxstatic

**Comment by jeremyatourville** [comment]
Oh, so very simply put - set an environment (shell) variable.  I was confusing the .env file with `env`

I see now my error message has changed and I have a very different issue to fix with permissions for the service account / user.  I am pretty sure I have it under control now.  That little clarification made all the difference.  Thanks!

**Comment by jeremyatourville** [comment]
I can confirm that watcher is now working to upload files.  Thanks!

**Comment by zirus001** [comment]
So I am running into the same issue. However, we are running the Stigman-watcher on our Windows server to import the checklist as well as running a DoD certificate on our Keycloak instance. I tried adding the following:
NODE_EXTRA_CA_CERTS=C:/path/to/file/dod-certs.pem
NODE_EXTRA_CA_CERTS=C:/path/to/file/individualca.crt
NODE_EXTRA_CA_CERTS=C:/path/to/file/individualsub-ca.crt
NODE_EXTRA_CA_CERTS=C:/path/to/file/signeddodcert.crt

None of these seem to be working. Does the NODE_EXTRA_CA_CERTS not work the same on windows?

**Comment by zirus001** [comment]
Disregard. For anyone that runs into this issue. Adding the NODE_EXTRA_CA_CERTS=C:/path/to/file/dod-certs.pem to the System environmental variable in Windows fixed the issue.
