### ISSUE TITLE
Unit tests for .ckl/.cklb/xccdf parser

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stigman-watcher#67]
Include test cases for:

- all import setting combinations
- files with invalid xml
- files with 0 reviews
- files with multiple STIGs
- files with duplicate Review Ids
- "normal" files (expected # of reviews, etc.)

**Comment by csmig** [comment]
Parser code was moved to https://github.com/NUWCDIVNPT/stig-manager-client-modules.
