### ISSUE TITLE
XCCDF Import Not Working

### ISSUE THREAD

**Issue by FWI-MPT** [NUWCDIVNPT/stigman-watcher#8]
Hello. We've got STIG Man Watcher working and importing CKL files placed in the watched directory, however, XCCDF imports do not work. I've increased the log file logging level to 'silly' and don't even see the XCCDF file being discovered by Watcher. Any thoughts?

**Comment by csmig** [comment]
Are you running Watcher with `--mode scan` or `WATCHER_MODE=scan`? It seems that scan mode is only processing extension `.ckl`, which is an oversight. But if you are experiencing this behavior in "events" mode then we have other concerns!

**Comment by csmig** [comment]
I'll push a release that fixes the issue in scan mode very soon. The oversight is on [this line](https://github.com/NUWCDIVNPT/stigman-watcher/blob/daacc346b47e731c2ded48e9cf7b12589848da0d/lib/scan.js#L37). It should read:

```
const stream = fg.stream([`${config.path}/**/*.ckl`, `${config.path}/**/*.xml`], {
```

**Comment by FWI-MPT** [comment]
Great. Thank you!
